* Drafting Notes on reply brief
** questions
*** In what order should you present the issues in the reply brief?
**** In chronological order: facts, issues, not in dispute

**** In order of importance: not disputed, facts, issues

**** In order of issues, with facts added
First point out that Appellee has not disputed the issues on appeal and that the Court should not search for its own arguments when the Appellee has failed argue for itself.

Then address Appellee's actual issues.

Then point out that appellee has made many mistakes in stating the facts and is not to be trusted.

*** How to present the issue of waiver?

Should not have to carry Appellee's water, or bear its burden. This implies that Appellee actually disputes, which we should not do.

Suggest the possibility that Appellee is waiving and invite the Court not to do Appellee's case. 

Invite the Court not to override the Appellee's decision on how to present its case.

"Appellee may be conceding these issues, but even if it is not, this Court need not argue against Appellant when Appellee refuses to argue for itself."

This Court need not argue against Appellant when Appellee refuses to do it itself. ????

Point out that Appellee is capably represented by counsel and that this Court need not ... override Appellee's counsel's choice on how to present its case.

Appellee is represented by experienced counsel who has made the choice not to oppose Appellant's arguments. This Court does not need to search out arguments on behalf of Appellee. (Don't ask too much, your point is made.)

** meta
Could Appellee intentionally be throwing the case, so that it would not be used as precedent?

If so, too much criticism of Appellee's case could make the Court to not publish the decision.




