* Respondent's Response
** Problems
*** did not cite any law for anything
*** did not explain why it was authorized to not consider Subject's sale a market sale, for any purpose, given that the Tribunal had found that it was a market sale.
*** did not explain why vacancy and the value of other properties determine whether a sale is a market sale,
*** did not explain what ecf study has to do with any of this
*** did not deny that Respondent will try to raise the taxes next year,
*** does not address the fact that the subject's tcv is based on its sale, not its record card, and that updating the record card next year and taxing petitioner for the additions would be double counting, since any "additions" have already been priced in.
*** a correct assessed value is important not just because it is required by statute, but because the SEV, essentially a corrected AV, is a ceiling on the TV. A ceiling that is too high could result in a value that is too high. For example, in a declining market, an AV that is too high could result in higher taxes. 
